### ISSUE TITLE
March 9th Patch

### ISSUE THREAD

**Issue by blayde911** [ravahn/BnS_ACT_Plugin#1]
First, I'd like to thank you very much for your work on this plugin (as well as FFXIV which I played for quite a while) 

I just wanted to mention that the March 9th patch appears to have broken the parser. I assume its a memory offset issue.

**Comment by ravahn** [comment]
Thanks for the report!

New offset is 0x00D71994, working on a release now.

**Comment by blayde911** [comment]
Damn, you work quickly. Thanks!

**Comment by edwinseneca** [comment]
hmm, still not working for me. Only my problem?

**Comment by ravahn** [comment]
What version # do you see for the BnS plugin on the ACT plugins tab? And, did you run ACT as an administrator?
EDIT: I just tested it to be sure, I didn't see a new BnS update and the plugin worked for me.  If you are directly using the .cs plugin file instead of a DLL, check to make sure the offset (line 334) matches 0x00D71994.

I may eventually submit this to Aditu as a downloadable plugin to simplify the update process, but I want to wait a little bit longer to see if I can solve some of the miscellaneous issues it still has - assigning certain effects to the Unknown combatant, for example, and requiring data to be shown on the #2 Combat tab.

**Comment by edwinseneca** [comment]
yeah, run as administrator, v0.1.0.3 
act 3.2.2.252

also been using your ffxiv plugins so I was really pleasantly surprised u made one here too ;)
maybe i have to restart my game?

**Comment by ravahn** [comment]
It seems like I'm going to have to embed some debugging information into the plugin to help troubleshoot issues.  This plugin is pretty simple - it reads loads a pointer to the chatlog location, parses the information out and saves it to a file.  Then, the file gets loaded up.

Try disabling other plugins, especially all FFXIV-related ones, and restart ACT.  I did write that plugin but it does some things to ACT to force it to read particular files / folders that will conflict with the BnS plugin.  I'll have to go back and see if I can make them play nicely with each other.

**Comment by edwinseneca** [comment]
ok, they were disabled but i will remove them from the plugin tab, then restart the game and act and see if any change.

**Comment by edwinseneca** [comment]
restarting the game did it.

Not sure if this is due to the fact I overwrote the older DLL with the newer, what is the recommended for upgrading, rename a new dll? or is there a better way.

Thanks!

I'm pretty sure I have relaunched the game after the patch yesterday. If that helps troubleshoot this later.

**Comment by ravahn** [comment]
I have a suspicion that if the BnS game installs a patch, the plugin cannot read data until the game restarts.  It probably is related to windows UAC.  

Nothing gets injected into the game process, so replacing the DLL and closing/reopening ACT will always load the newer version.  You can also unload/reload the plugin inside ACT without restarting it.

Since this is resolved, closing this issue.
